-- MySQL Script generated by MySQL Workbench
-- Fri Nov  8 10:49:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_enquete
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_enquete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_enquete` DEFAULT CHARACTER SET utf8 ;
USE `db_enquete` ;

-- -----------------------------------------------------
-- Table `db_enquete`.`tb_eleitorado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_enquete`.`tb_eleitorado` (
  `id_eleitores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`id_eleitores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_enquete`.`tb_candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_enquete`.`tb_candidatos` (
  `id_candidatos` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(60) NULL,
  `lider` VARCHAR(60) NULL,
  `email` VARCHAR(60) NULL,
  `votos` INT NULL,
  PRIMARY KEY (`id_candidatos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Inserindo os candidatos 
-- -----------------------------------------------------
INSERT INTO tb_candidatos 
(
	tema, lider, email, votos
) 
    VALUES
(
	'Scrum', 'Pedro', 'pedro@hotmail.com', '0'
),
(
	'E-Kanban', 'Tiago', 'tiago@hotmail.com', '0'
),
(
	'Industri 4.0', 'João', 'joao@hotmail.com', '0'
);    